projects:
  # - name: Daydream
  #   desc: 简洁优雅、功能强大的 Typecho 博客主题。
  #   url: Skywt2003/Daydream
  - name: Daydreamer
    desc: 基于 Astro 打造的网站系统，即本网站。
    url: Skywt2003/Daydreamer
  - name: Writecho
    desc: 纯手写的 Typecho 博客主题。
    url: Skywt2003/Writecho
  - name: kindle-zhcn-clippings-to-json
    desc: Kindle 书摘解析器 npm 模块。
    url: Skywt2003/kindle-zhcn-clippings-to-json
  - name: sky
    desc: 基于 Argon 的 Typecho 博客主题。
    url: Skywt2003/sky
  - name: PasteBurn
    desc: 阅后即焚，守护隐私。
    url: Skywt2003/PasteBurn
  - name: WebCV
    desc: 简洁的 Web 简历生成器。
    url: Skywt2003/WebCV
