groups:
  - name: 🌟 公共服务
    services:
      - name: Blog
        app: Typecho 旧博客
        url: https://blog.skywt.cn
        method: Docker, Upyun
      # - name: Whisper
      #   app: WordPress 子博客
      #   url: https://whisper.skywt.cn
      #   method: Docker 🚧
      - name: Write
        app: Typecho 手写博客
        url: https://write.skywt.cn
        method: Docker, Upyun
      - name: Books
        app: Calibre-web 电子书管理
        url: https://books.skywt.cn
        method: Docker
      - name: Drop
        app: Snapdrop 文件传输
        url: https://drop.skywt.cn
        method: Docker
      - name: CV
        app: WebCV 在线简历
        url: https://cv.skywt.cn
        method: Vercel, DogeCloud
  - name: 👨‍💻 效率工具
    services:
      - name: Memos
        app: memos 卡片笔记
        url: https://memos.skywt.cn
        method: Docker
      - name: Password
        app: VaultWarden 密码管理
        url: https://pass.skywt.cn
        method: Docker
      - name: Chat
        app: NextChat GPT 客户端
        url: https://chat.skywt.cn
        method: Vercel
      - name: ChatGPT
        app: Better ChatGPT 客户端
        url: https://chatgpt.skywt.cn
        method: Vercel
      - name: RSS
        app: FreshRSS 在线阅读器
        url: https://rss.skywt.cn
        method: Docker
      - name: RSSHub
        app: RSSHub
        url: https://rsshub.skywt.cn
        method: Docker
      - name: WeRSS
        app: 微信公众号 RSS
        url: https://werss.skywt.cn
        method: Docker
      - name: Archive
        app: ArchiveBox 网页存档
        url: https://archive.skywt.cn
        method: Docker
  - name: 🛠️ 开发与运维
    services:
      - name: Git
        app: Gitea 代码仓库
        url: https://git.skywt.cn
        method: Docker
      - name: Code
        app: Code-server 编辑器
        url: https://code.skywt.cn
        method: Docker
      - name: Frp
        app: Frp 内网穿透
        url: https://frp.skywt.cn
        method: Docker
      - name: VPN
        app: Headscale 虚拟专用网络
        url: https://vpn.skywt.cn
        method: Docker
      - name: Push
        app: Bark iOS 推送服务
        url: https://push.skywt.cn
        method: Docker
      - name: Minecraft
        app: Minecraft 服务器
        url:
        method: Docker 💤
        status: stopped
  - name: 🗃️ 文件存储
    services:
      - name: Cloud
        app: Nextcloud 云套件
        url: https://cloud.skywt.cn
        method: Docker
      - name: Drive
        app: Cloudreve 云盘
        url: https://drive.skywt.cn
        method: Docker
      - name: WebDAV
        app: WebDAV
        url: https://webdav.skywt.cn
        method: Docker
      # - name: Object Storage
      #   app: MinIO 对象存储
      #   url: https://os.skywt.cn
      #   method: Docker
  - name: ⚙️ 管理工具
    services:
      - name: Auth
        app: Keycloak 单点登录
        url: https://auth.skywt.cn
        method: Docker
      - name: Analytics
        app: Matomo 访客统计
        url: https://analytics.skywt.cn
        method: Docker
      - name: Console
        app: Cockpit 控制面板
        url: https://console.skywt.cn
        method: Systemd
      # - name: pgAdmin
      #   app: pgAdmin
      #   url: https://pgadmin.skywt.cn
      #   method: Docker 💤
      #   status: stopped
      - name: phpMyAdmin
        app: phpMyAdmin
        url: https://phpmyadmin.skywt.cn
        method: Docker
      - name: Uptime
        app: Upptime 服务器监控
        url: https://uptime.skywt.cn
        method: GitHub Actions
      - name: Status
        app: Netdata 服务器监控
        url: https://status.skywt.cn
        method: Systemd
      # - name: Dashboard
      #   app: Grafana 数据面板
      #   url: https://dash.skywt.cn
      #   method: Docker
