friends:
  - name: fzf404
    desc: 左派社会主义接班人
    url: https://www.fzf404.art/
    avatar: https://img.fzf404.art/avatar.webp
  - name: 甘小蔗
    desc: Ganxiaozhe's Values
    url: https://gxzv.com/
  - name: 枝因
    desc: 「Oh god, these stars. 」
    url: https://viyi.cc/
  - name: Ayu
    desc: 「三脚猫多面手，努力学习世界的一切。」
    url: https://ayu.land/
  - name: 昼河万里
    desc: 「一起去看月亮吧。」
    url: https://tothemoonriver.icu/
  - name: Hzao
    desc: 「」
    url: https://blog.hzao.top/
  - name: 安擎
    desc: 「By the power of language. 」
    url: https://angine.tech/
  - name: widcardw
    desc: 「不是多面手。」
    url: https://widcard.win/
  - name: 山川行貉
    desc: 「快让我在雪地上撒点儿野。」
    url: https://www.scxho.cn/
  - name: 明石
    desc: 「青春无悔热爱。」
    url: https://imakashi.eu.org/
  - name: Leo's
    desc: 「THIS IS MY STORY. 」
    url: https://www.isolitude.cn/
  - name: idealclover
    desc: 「Stay simple, stay naive. 」
    url: https://idealclover.top/
  - name: 张哄 Heo
    desc: 「分享设计与科技生活。」
    url: https://blog.zhheo.com/
  - name: 一蓑烟雨
    desc: 「一蓑烟雨任平生。」
    url: https://easyf12.top/
  - name: 折影轻梦
    desc: 「纯粹、热爱、勇敢。」
    url: https://nexmoe.com/
  - name: Sun
    desc: 「自强不息，厚德载物。」
    url: https://www.iaesun.com/
