types:
  - name: 公共服务
    services:
      - name: Blog
        app: Typecho
        url: https://blog.skywt.cn
        method: Docker
      - name: Whisper
        app: WordPress
        url: https://whisper.skywt.cn
        method: Docker
      - name: Write
        app: Typecho
        url: https://write.skywt.cn
        method: Docker
      - name: Books
        app: Calibre-web
        url: https://books.skywt.cn
        method: Docker
      - name: Drop
        app: Snapdrop
        url: https://drop.skywt.cn
        method: Docker
  - name: 开发与工具
    services:
      - name: Memos
        app: memos
        url: https://memos.skywt.cn
        method: Docker
      - name: ChatGPT
        app: Better ChatGPT
        url: https://chat.skywt.cn
        method: Docker
      - name: Docs
        app: Outline
        url: https://docs.skywt.cn
        method: Docker
      - name: Papers
        app: Paperless-ngx
        url: https://paper.skywt.cn
        method: Docker
      - name: Code
        app: Code-server
        url: https://code.skywt.cn
        method: Docker
      - name: Git
        app: Gitea
        url: https://git.skywt.cn
        method: Docker
      - name: Minecraft
        app: Minecraft Server
        url:
        method: Docker
      - name: RSS
        app: FreshRSS
        url: https://rss.skywt.cn
        method: Docker
      - name: RSSHub
        app: RSSHub
        url: https://rsshub.skywt.cn
        method: Docker
      - name: Reading List
        app: Wallabag
        url: https://mark.skywt.cn
        method: Docker
      - name: Archive
        app: ArchiveBox
        url: https://archive.skywt.cn
        method: Docker
      - name: Password
        app: VaultWarden
        url: https://pass.skywt.cn
        method: Docker
      - name: Analytics
        app: Matomo
        url: https://analytics.skywt.cn
        method: Docker
      - name: Auth
        app: Keycloak
        url: https://auth.skywt.cn
        method: Docker
      - name: Frp
        app: Frp
        url: https://frp.skywt.cn
        method: Docker
      - name: VPN
        app: Headscale
        url: https://vpn.skywt.cn
        method: Docker
  - name: 文件存储
    services:
      - name: Cloud
        app: Nextcloud
        url: https://cloud.skywt.cn
        method: Docker
      - name: Drive
        app: Cloudreve
        url: https://drive.skywt.cn
        method: Docker
      - name: WebDAV
        app: WebDAV
        url: https://webdav.skywt.cn
        method: Docker
      - name: ObS
        app: MinIO
        url: https://os.skywt.cn
        method: Docker
  - name: 管理工具
    services:
      - name: Console
        app: Cockpit
        url: https://console.skywt.cn
        method: Systemd
      - name: pgAdmin
        app: pgAdmin
        url: https://pgadmin.skywt.cn
        method: Docker
      - name: phpMyAdmin
        app: phpMyAdmin
        url: https://phpmyadmin.skywt.cn
        method: Docker
      - name: Uptime
        app: Upptime
        url: https://uptime.skywt.cn
        method: GitHub Actions
      - name: Status
        app: Netdata
        url: https://status.skywt.cn
        method: Docker
      - name: Dashboard
        app: Grafana
        url: https://dash.skywt.cn
        method: Docker
